version: '3.7'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  site:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - server
    links:
      - server
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: site.localtest.me
      VIRTUAL_PORT: 3000
      REACT_APP_API_URL: http://server.localtest.me

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - '8888:8888'
    depends_on:
      - dockerhost
    links:
      - dockerhost
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: server.localtest.me
      VIRTUAL_PORT: 8888
      DATABASE_URL: postgres://postgres:@dockerhost:5432/lotus-2?sslmode=disable
      DATABASE_POOL_MIN: 0
      DATABASE_POOL_MAX: 10
      ENABLE_NODE_CLUSTER: 'false'
